name = "CosmoCentralDocs"
uuid = "a29e4abb-1a46-4601-85ad-a0258fddbceb"
authors = ["Marco Bonici <bonici.marco@gmail.com>"]
version = "0.1.0"

[deps]
CosmoCentral = "ad8f630a-9b1f-4174-92d0-7638535e3d6b"
