name = "CosmoCentralDocs"
uuid = "ad8f930a-9b1f-4844-93h0-7638947e3h4b"
authors = ["marcobonici <bonici.marco@gmail.com>"]
version = "0.1.0"

[deps]
CosmoCentral = "ad8f630a-9b1f-4174-92d0-7638535e3d6b"
